### ISSUE TITLE
アプリケーションbuild時にコンパイルエラー

### ISSUE THREAD

**Issue by zgock999** [dotprologue/ScenarioFlow#1]
お疲れ様です。
Assets\ScenarioFlow\ScenarioScripts\Composite\Editor\CompositeScenarioScriptEditor.csに
#if UNITY_EDITOR宣言が抜けておりまして、アプリケーションbuildが通りませんでした。
すぐ直せるとこだったので手元では直しましたが修正をお願いします

**Comment by ito-akira-dp** [comment]
開発者の伊都アキラです。

ご指摘のエラーが発生することを、こちらでも確認しました。
CompositeScenarioScriptEditor.csはリリース直前に追加したスクリプトで、ビルドテストの再試行を失念しておりました......
このバグについては次バージョンで修正しますので、しばらくお待ちください。

ご報告、ありがとうございました！

**Comment by ito-akira-dp** [comment]
バージョン1.1.0にて、こちらのバグは修正されました。
また何か不具合があれば、よろしくお願いします！

**Comment by ito-akira-dp** [comment]
こちらのバグは、バージョン1.1.0にて修正されました。
また何か不具合があれば、お伝えください！
